<?php //

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @category app
 * @package views/vias
 * @author Lázaro Nieto Aranda
 * @date 27-abr-2015
 * @time 18:21:27
 */
 // Establecer formado de Excel
header("Content-Type: application/vnd.ms-excel");

// nombre del archivo
header('Content-Disposition: attachment; filename="Via '.$via.'.xls"');

//forzar a descarga por el navegador
$objWriter->save('php://output');
