<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @category app
 * @package views/entradas
 * @author Lázaro Nieto Aranda
 * @date 06-may-2015
 * @time 11:38:47
 */

View::flash(); ?>
<?php View::process($page_module, $page_title, $set_title); ?>
<div class="container shell-view">
    <div class="row">
        <?php echo DwForm::open('', '', array('id'=>'form-registro', 'class'=>'')); ?>
        <div class="col-md-1">&nbsp;</div>
        <div class="col-md-4">
            <?php echo DwForm::select('año',array('2015'=>'2015', '2016'=>'2016', '2017'=>'2017', '2018'=>'2018'), array('class'=>''),date('Y'),'Año'); ?>
        </div>
        <div class="form-actions">
                <?php echo DwForm::submit('mostrar'); ?>
            </div>
        <?php echo DwForm::close(); ?>
    </div>
    <div class="row">
        <div id="grafico2"></div>
    </div>
</div>
<?php echo Tag::js('highcharts/highcharts').PHP_EOL; ?>
<?php echo Tag::js('highcharts/highcharts-3d').PHP_EOL; ?>
<?php echo Tag::js('highcharts/exporting').PHP_EOL; ?>
<script type="text/javascript">
    $(function () {
    $('#grafico2').highcharts({

        chart: {
            type: 'column',
            options3d: {
                enabled: true,
                alpha: 15,
                beta: 15,
                viewDistance: 80,
                depth: 40
            },
            marginTop: 80,
            marginRight: 40
        },

        title: {
            text: 'Total movimiento de vagones anual'
        },

        xAxis: {
            categories: ['Enero', 'Febre', 'Marzo', 'Abril','Mayo','Junio','Julio','Agosto','Septi','Octu','Novi','Dici']
        },

        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: 'Numero de vagones'
            }
        },

        tooltip: {
            headerFormat: '<b>{point.key}</b><br>',
            pointFormat: '<span style="color:{series.color}">\u25CF</span> {series.name}: {point.y} / {point.stackTotal}'
        },

        plotOptions: {
            column: {
                stacking: 'normal',
                depth: 40
            }
        },

        series: [{
            name: 'Ingles',
            data: [<?php echo $inglEner->total; ?>,<?php echo $inglFebr->total; ?>,<?php echo $inglMarz->total; ?>,<?php echo $inglAbri->total; ?>,<?php echo $inglMayo->total; ?>,<?php echo $inglJuni->total; ?>,
                   <?php echo $inglJuli->total; ?>,<?php echo $inglAgos->total; ?>,<?php echo $inglSept->total; ?>,<?php echo $inglOctu->total; ?>,<?php echo $inglNovi->total; ?>,<?php echo $inglDici->total; ?> ],
            stack: 'male'
            
        }, {
            name: 'Aleman',
            data: [<?php echo $alemEner->total; ?>,<?php echo $alemFebr->total; ?>,<?php echo $alemMarz->total; ?>,<?php echo $alemAbri->total; ?>,<?php echo $alemMayo->total; ?>,<?php echo $alemJuni->total; ?>,
                   <?php echo $alemJuli->total; ?>,<?php echo $alemAgos->total; ?>,<?php echo $alemSept->total; ?>,<?php echo $alemOctu->total; ?>,<?php echo $alemNovi->total; ?>,<?php echo $alemDici->total; ?> ],
            stack: '3male'
        }, {
            name: 'Autos',
            data: [<?php echo $autoEner->total; ?>,<?php echo $autoFebr->total; ?>,<?php echo $autoMarz->total; ?>,<?php echo $autoAbri->total; ?>,<?php echo $autoMayo->total; ?>,<?php echo $autoJuni->total; ?>,
                   <?php echo $autoJuli->total; ?>,<?php echo $autoAgos->total; ?>,<?php echo $autoSept->total; ?>,<?php echo $autoOctu->total; ?>,<?php echo $autoNovi->total; ?>,<?php echo $autoDici->total; ?> ],
            stack: '2male'
        }, {
            name: 'Contenedor',
            data: [<?php echo $portEner->total; ?>,<?php echo $portFebr->total; ?>,<?php echo $portMarz->total; ?>,<?php echo $portAbri->total; ?>,<?php echo $portMayo->total; ?>,<?php echo $portJuni->total; ?>,
                   <?php echo $portJuli->total; ?>,<?php echo $portAgos->total; ?>,<?php echo $portSept->total; ?>,<?php echo $portOctu->total; ?>,<?php echo $portNovi->total; ?>,<?php echo $portDici->total; ?> ],
            stack: '1male'
        }]
    });
});
</script>