<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @category app
 * @package vews/vias
 * @author Lázaro Nieto Aranda
 * @date 21-abr-2015
 * @time 23:40:37
 */
?>

<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>
    <div class="container-overflow">
        <div class="print">
            <table class="table table-bordered table-hover table-striped table-condensed table-responsive" id="via">
                <thead>
                    <tr>
                        <th></th>                        
                        <th>VAGÓN</th>
                        <th>CAJA 1</th>
                        <th>CAJA 2</th>
                        <th>TIPO</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if($vagones) { ?>
                        <?php $linea=1; ?>
                        <?php foreach($vagones as $row): ?>
                            <tr>
                                <td><?php echo $linea; ?></td>
                                <td><?php echo $row->id_vagon; ?></td>
                                <td><?php echo $row->caja1; ?></td>
                                <td><?php echo $row->caja2; ?></td>
                                <td><?php echo $row->tipo->tipo; ?></td>
                            </tr>
                            <?php $linea++ ?>
                        <?php endforeach; ?>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <div class="">
            <table class="table table-responsive">
                <tr>
                    <td style="text-align: center"><a href="http://localhost/teryma/teryma/vias/pdf/index/<?php echo $via; ?>/" target="_blank"><?php echo DwHtml::img("pdf.png", 'exportar a pdf', array('id'=>'pdf')); ?></a></td>
                    <td style="text-align: center"><a href="http://localhost/teryma/teryma/vias/excel/index/<?php echo $via; ?>/" target="_blank"><?php echo DwHtml::img("excel.png", 'exportar a excel', array('id'=>'excel')); ?></a></td>
                    <td style="text-align: center"><?php echo DwHtml::img("print.png", 'imprimir', array('id'=>'printer', 'onclick'=>'printt()')); ?></td>
                </tr>
            </table>            
        </div>
    </div>
</div>
<script type="text/javascript">
function printt () {
  var divToPrint=document.getElementById('via');
  newWin= window.open("","","height=100%");
  newWin.document.write(divToPrint.outerHTML);
//  var nuevo=newWin.document.getElementById('via');
//  nuevo.style.width = 100%;
  newWin.print();
  newWin.close();
  }
</script>