<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @category app
 * @package views/entradas
 * @author Lázaro Nieto Aranda
 * @date 02-may-2015
 * @time 8:27:52
 */

View::flash(); ?>
<?php View::process($page_module, $page_title, $set_title); ?>
<div class="container shell-view">
    
    
    <div class="row">
        <?php echo DwForm::open('', '', array('id'=>'form-tren', 'class'=>'')); ?>
        <div class="col-md-1">&nbsp;</div>
        <div class="col-md-4">
            <?php echo DwForm::date('tren.fecha_at',array('class'=>'input-required'), date("Y-m-d"), 'Fecha'); ?>
            <?php echo DwForm::time('tren.hora_at',array('class'=>'input-required'), date("H:i:s"), 'Hora'); ?>
            <?php echo DwForm::number('tren.vagones', array('class'=>'input-required','min'=>"0" ,'step'=>"0"), null, 'Nª de vagones'); ?>
        </div>
        <div class="col-md-1">&nbsp;</div>
        <div class="col-md-4">
            <?php echo DwForm::select('tren.tipo',array('salida'=>'Salida', 'entrada'=>'Entrada'), array('class'=>'input-required'),'Salida', 'Tipo'); ?>
            <?php echo DwForm::select('tren.vias_id',array('0'=>'0', '1'=>'1', '2'=>'2'), array('class'=>'input-required'),'0','Vía'); ?>
            <div class="form-actions">
                <?php echo DwForm::send('Guardar tren'); ?>
                <?php echo DwForm::cancel(); ?>
            </div>
        </div>
    </div>
    <?php echo DwForm::close(); ?>
</div>
